baseURL = '/'
languageCode = 'en-us'
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
theme = "hugo-whisper-theme"
title = 'Malaria Modeling Faculty Enrichment Program 2022'
[menu]
[[menu.main]]
name = 'Home'
pageref = '/'
weight = 1
[[menu.main]]
name = 'Lessons'
pageref = '/lessons/'
weight = 2
[[menu.main]]
name = 'Modules'
pageref = '/modules/'
weight = 3
[[menu.main]]
name = 'Resources'
pageref = '/resources/'
weight = 4


[module]
[module.hugoVersion]
extended = true
min = '0.55.0'
summaryLength = 30


[params]
google_analytics_id = ''
homepage_image = '/images/numm-logo.svg'
homepage_intro = 'Lorem Ipsum'
mainSections = ['lessons', 'modules', 'resources']


[params.homepage_meta_tags]
meta_description = 'Materials for Malaria Modeling Faculty Enrichment Program 2022'
meta_og_description = 'Materials for Malaria Modeling Faculty Enrichment Program 2022'
meta_og_image = '/images/numm-logo.svg'
meta_og_title = 'Malaria Modeling Faculty Enrichment Program 2022'
meta_og_type = 'website'
meta_og_url = 'https://faculty-enrich-2022.netlify.app'
meta_twitter_card = 'summary'
meta_twitter_creator = '@nu_modeling'
meta_twitter_site = '@nu_modeling'

[params.logo]
mobile = '/images/small_logo.svg'
standard = '/images/small_logo.svg'

[outputFormats]
  [outputFormats.html]
    isPlainText = true

[markup.goldmark.renderer]
unsafe = true